name: EntitySpawnManager
version: 1.2.1
api-version: 1.16
author: GibMirRechte
main: de.msm.main.MobSpawnManager
website: https://discord.gg/yhBX6KT
commands:
   managegui:
      description: Edit the config.yml without open it