name: EntitySpawnManager
version: 1.3.0
api-version: 1.16
author: GibMirRechte
main: de.msm.main.EntitySpawnManager
website: https://discord.gg/yhBX6KT
commands:
   managegui:
      description: Edit the config.yml without open it